# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy
---
policy:
  - section:
      - id: ["versions"]
        label:
          - name: "ver: 1.x"
            keys: ["v1_x", "v1.X", "1.x"]
          - name: "ver: 2.0.x"
            keys: ["v2_0", "v2.0", "2.0.x"]
          - name: "ver: 2.1.x"
            keys: ["v2_1", "v2.1", "2.1.x"]
          - name: "ver: 2.2.x"
            keys: ["v2_2", "v2.2", "2.2.x"]
          - name: "ver: 2.3.x"
            keys: ["v2_3", "v2.3", "2.3.x"]
          - name: "ver: 2.4.x"
            keys: ["v2_4", "v2.4", "2.4.x"]
          - name: "ver: 2.5.x"
            keys: ["v2_5", "v2.5", "2.5.x"]
          - name: "ver: 2.5.x"
            keys: ["master"]
