app:
  - "src/lightning/app/**"
  - "src/lightning_app/*"
  - "tests/tests_app/**"
  - "tests/tests_cli/**"
  - "tests/integrations_app/**"
  - "tests/integrations_app_examples/**"
  - "examples/app/**"
  - "docs/source-app/**"
  - "requirements/app/**"

pl:
  - "src/lightning/pytorch/**"
  - "src/pytorch_lightning/*"
  - "tests/tests_pytorch/**"
  - "tests/legacy/**"
  - "examples/pytorch/**"
  - "docs/source-pytorch/**"
  - "requirements/pytorch/**"

fabric:
  - "src/lightning/fabric/**"
  - "src/lightning_fabric/*"
  - "tests/tests_fabric/**"
  - "examples/fabric/**"
  - "docs/source-fabric/**"
  - "requirements/fabric/**"

ci:
  - ".actions/**"
  - ".azure/**"
  - ".github/**"
  - "dockers/**"
  - ".pre-commit-config.yml"
