# see https://docs.codecov.io/docs/codecov-yaml
# Validation check:
# $ curl --data-binary @.codecov.yml https://codecov.io/validate

# https://docs.codecov.io/docs/codecovyml-reference
codecov:
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  require_ci_to_pass: yes
  notify:
    # after_n_builds: 2
    wait_for_ci: yes

coverage:
  precision: 0 # 2 = xx.xx%, 0 = xx%
  round: nearest # how coverage is rounded: down/up/nearest
  range: 40...100 # custom range of coverage colors from red -> yellow -> green
  status:
    # https://codecov.readme.io/v1.0/docs/commit-status
    project:
      default:
        target: 99% # specify the target coverage for each commit status
        threshold: 30% # allow this little decrease on project
        # https://github.com/codecov/support/wiki/Filtering-Branches
        # branches: main
        if_ci_failed: error
    # https://github.com/codecov/support/wiki/Patch-Status
    patch:
      default:
        target: 50% # specify the target "X%" coverage to hit
        # threshold: 50% # allow this much decrease on patch
    changes: false

# https://docs.codecov.com/docs/github-checks#disabling-github-checks-patch-annotations
github_checks:
  annotations: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false

comment:
  layout: header, diff
  require_changes: false
  behavior: default # update if exists else create new
  # branches: *
