trigger:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

timeout: "60" # minutes
machine: "L4_X_2"
image: "nvidia/cuda:12.6.3-runtime-ubuntu22.04"
parametrize:
  matrix: {}
  include:
    # note that this is setting also all oldest requirements which is linked to Torch == 2.1
    - image: "pytorchlightning/pytorch_lightning:base-cuda12.1.1-py3.10-torch2.1"
      PACKAGE_NAME: "fabric"
      python_version: "3.10"
    - PACKAGE_NAME: "fabric"
      python_version: "3.12"
    # - image: "nvidia/cuda:12.6-runtime-ubuntu22.04"
    #   PACKAGE_NAME: "fabric"
    - PACKAGE_NAME: "lightning"
      python_version: "3.12"
  exclude: []

env:
  FREEZE_REQUIREMENTS: "1"
  RUN_ONLY_CUDA_TESTS: "1"

run: |
  whereis nvidia
  nvidia-smi
  python --version
  pip --version
  pip install -q fire wget packaging
  pip list
  set -ex

  CUDA_VERSION="${image##*cuda}" # Remove everything up to and including "cuda"
  echo "Using CUDA version: ${CUDA_VERSION}"
  CUDA_VERSION_M_M="${CUDA_VERSION%.*}"  # "12.6"
  CUDA_VERSION_MM="${CUDA_VERSION_M_M//./}"  # "126"
  export UV_TORCH_BACKEND=cu${CUDA_VERSION_MM}
  COVERAGE_SOURCE=$(python -c 'n = "${PACKAGE_NAME}" ; print(dict(fabric="lightning_fabric").get(n, n))')
  echo "collecting coverage for: ${COVERAGE_SOURCE}"
  TORCH_VER=$(python -c "import torch; print(torch.__version__.rsplit('.', 1)[0])")

  if [ "${TORCH_VER}" == "2.1" ]; then
    echo "Set oldest versions"
    pip uninstall -y deepspeed
    pip install -U "lightning-utilities[cli]"
    cd requirements/fabric
    python -m lightning_utilities.cli requirements set-oldest --req_files "['base.txt', 'strategies.txt']"
    python -m lightning_utilities.cli requirements prune-pkgs --packages deepspeed --req_files strategies.txt
    cd ../..
    pip install "cython<3.0" wheel  # for compatibility
  fi

  echo "Adjust torch versions in requirements files"
  PYTORCH_VERSION=$(python -c "import torch; print(torch.__version__.split('+')[0])")
  pip install -q wget packaging
  python -m wget https://raw.githubusercontent.com/Lightning-AI/utilities/main/scripts/adjust-torch-versions.py
  for fpath in `ls requirements/**/*.txt`; do \
    python ./adjust-torch-versions.py $fpath ${PYTORCH_VERSION}; \
  done

  if [ "${PACKAGE_NAME}" == "fabric" ]; then
    echo "Replaced PL imports"
    pip install -U -q -r .actions/requirements.txt
    python .actions/assistant.py copy_replace_imports --source_dir="./tests/tests_fabric" \
      --source_import="lightning.fabric" \
      --target_import="lightning_fabric"
    python .actions/assistant.py copy_replace_imports --source_dir="./examples/fabric" \
      --source_import="lightning.fabric" \
      --target_import="lightning_fabric"
  fi

  echo "Install package with [${PACKAGE_NAME}] extras"
  extra=$(python -c "print({'lightning': 'fabric-'}.get('${PACKAGE_NAME}', ''))")
  uv pip install ".[${extra}dev]" --upgrade

  python requirements/collect_env_details.py
  python -c "import torch ; mgpu = torch.cuda.device_count() ; assert mgpu >= 2, f'GPU: {mgpu}'"
  python requirements/pytorch/check-avail-extras.py
  python -c "import bitsandbytes"

  echo "Testing: Fabric doctests"
  if [ "${PACKAGE_NAME}" == "fabric" ]; then
    cd src/
    python -m pytest lightning_fabric
    cd ..
  fi

  cd tests/
  echo "Testing: fabric standard"
  python -m coverage run --source ${COVERAGE_SOURCE} -m pytest tests_fabric/ -v --durations=50

  echo "Testing: fabric standalone"
  export PL_RUN_STANDALONE_TESTS=1
  wget https://raw.githubusercontent.com/Lightning-AI/utilities/main/scripts/run_standalone_tests.sh
  bash ./run_standalone_tests.sh "tests_fabric"
  export PL_RUN_STANDALONE_TESTS=0

  #  echo "Reporting coverage" # todo
  #  python -m coverage report
  #  python -m coverage xml
  #  python -m coverage html

  # TODO: enable coverage
  #  # https://docs.codecov.com/docs/codecov-uploader
  #  curl -Os https://uploader.codecov.io/latest/linux/codecov
  #  chmod +x codecov
  #  ./codecov --token=$(CODECOV_TOKEN) --commit=$(Build.SourceVersion) \
  #    --flags=gpu,pytest,${COVERAGE_SOURCE} --name="GPU-coverage" --env=linux,azure
  #  ls -l
  cd ..

  echo "Testing: fabric examples"
  cd examples/
  bash run_fabric_examples.sh --accelerator=cuda --devices=1
  bash run_fabric_examples.sh --accelerator=cuda --devices=2 --strategy ddp
