name: Typos and doc fixes
description: Tell us about how we can improve our documentation
labels: ["needs triage", "docs"]
body:
  - type: textarea
    attributes:
      label: ðŸ“š Documentation
      description: A description of the ðŸ›bugðŸ›.
      placeholder: |
        For typos and doc fixes, please go ahead and:

        - For a simlpe typo or fix, please send directly a PR (no ned to create an issue)
        - If you are not sure about the proper solution, please describe here your finding...

    validations:
      required: true

  - type: markdown
    attributes:
      value: >
        ### If you enjoy Lightning, check out our other projects! âš¡

        - [**Metrics**](https://github.com/Lightning-AI/metrics):
          Machine learning metrics for distributed, scalable PyTorch applications.
          enables pure PyTorch users to scale their existing code on any kind of device while retaining full control over their own loops and optimization logic.
        - [**Flash**](https://github.com/Lightning-AI/lightning-flash):
          The fastest way to get a Lightning baseline! A collection of tasks for fast prototyping, baselining, fine-tuning, and solving problems with deep learning.
        - [**Bolts**](https://github.com/Lightning-AI/lightning-bolts):
          Pretrained SOTA Deep Learning models, callbacks, and more for research and production with PyTorch Lightning and PyTorch.
