name: Report a bug
description: Errors and regression reports with complete reproducing test cases.
labels: ["needs triage", "bug"]
body:
  - type: markdown
    attributes:
      value: >
        WAIT!
        
        Before you go any further. Is this really a **ðŸ› bug**? 
        
        If it's a question about how Lightning works, have a look at our [Lightning documentation](https://lightning.ai/lightning-docs/)
        or ask a question on our [Community Slack](https://pytorch-lightning.slack.com).
        
        If it really is a **ðŸ› bug**, please fill out this form as completely as you can.

  - type: markdown
    attributes:
      value: >
        If you're new to making bug reports, here are a few guidelines for you:

        1. Please K.I.S.S. > Keep It Short and Succinct. From the description, to steps to reproduce the bug, to the code example, and to any additional info, try and keep everything as concise as possible.

        2. Bugs with code are fixed faster! Please provide a clear and concise code example that reproduces the problem. To get that use the [BoringModel] (https://colab.research.google.com/github/Lightning-AI/lightning/blob/master/examples/pl_bug_report/bug_report_model.ipynb)!

         IMPORTANT: This is going to be public, so please choose wisely.

         If you could not reproduce the bug using the BoringModel and still think there's a bug, please make out a bug report.

        3. Povide anything else that you think may help us reproduce your issue.

  - type: checkboxes
    id: checks
    attributes:
      label: First check
      description: Please confirm and check all the following options.
      options:
        - label: I'm sure this is a bug.
          required: true
        - label: I've added a descriptive title to this bug.
          required: true
        - label: I've provided clear instructions on how to reproduce the bug.
          required: true
        - label: I've added a code sample.
          required: true
        - label: I've provided any other important info that is required.
          required: true

  - type: textarea
    attributes:
      label: Bug description
      description: A clear and concise description of the ðŸ›bugðŸ›.
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to reproduce the bug
      description: >
        Provide steps and example code here.
      placeholder: "# Insert code here"
      render: python
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error messages and logs
      description: >
        Provide any error messages and/or logs
      placeholder: "# Copy the complete error messages and logs"
      value: |
        ```

        # Error messages and logs here please

        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: Important info
      description: >
        Provide all the following info
      value: |
        ```

        #- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
        #- PyTorch Lightning Version (e.g., 1.5.0):
        #- Lightning App Version (e.g., 0.5.2):
        #- PyTorch Version (e.g., 1.10):
        #- Python version (e.g., 3.9):
        #- OS (e.g., Linux):
        #- CUDA/cuDNN version:
        #- GPU models and configuration:
        #- How you installed Lightning(`conda`, `pip`, source):
        #- Running environment of LightningApp (e.g. local, cloud):

        ```
    validations:
      required: true

  - type: textarea
    attributes:
      label: More info
      description: Add any other info about the issue here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Happy engineering!**"
