from pytorch_lightning.metrics.metric import Metric

from pytorch_lightning.metrics.classification.accuracy import Accuracy
from pytorch_lightning.metrics.regression.mean_squared_error import MeanSquaredError
