# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  tags:
    include:
      - '*'
  branches:
    include:
      - "master"
      - "release/*"
      - "refs/tags/*"

pr: none

schedules:
  - cron: "0 0 * * *" # At the end of every day
    displayName: Daily midnight benchmark
    branches:
      include:
        - "master"

jobs:
  - job: benchmarks
    timeoutInMinutes: "90"
    cancelTimeoutInMinutes: "2"
    pool: gridai-spot-pool
    container:
      # should match the one in '.azure-pipelines/gpu-benchmark.yml'
      image: "pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.8"
      options: "--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all --shm-size=32g"
    workspace:
      clean: all

    steps:
      - bash: |
          python -m pytest tests/benchmarks -v --durations=0
        displayName: 'Testing: benchmarks'
        env:
          PL_RUNNING_BENCHMARKS: 1
