name: Call building packages

on:
  workflow_call:
    inputs:
      artifact-name:
        description: "Unique name for collecting artifacts"
        required: true
        type: string
      pkg-names:
        description: "list package names to be build in json format"
        required: false
        type: string
        default: |
          ["lightning", "fabric", "pytorch"]

defaults:
  run:
    shell: bash

jobs:
  build-packages:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pkg-name: ${{ fromJSON(inputs.pkg-names) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.x"

      - run: python -c "print('NB_DIRS=' + str(2 if '${{ matrix.pkg-name }}' == 'pytorch' else 1))" >> $GITHUB_ENV
      - name: Build & check package
        uses: ./.github/actions/pkg-check
        with:
          pkg-name: ${{ matrix.pkg-name }}
          nb-dirs: ${{ env.NB_DIRS }}

      - run: |
          mkdir -p pypi/${{ matrix.pkg-name }}
          cp dist/* pypi/${{ matrix.pkg-name }}/

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.artifact-name }}-${{ matrix.pkg-name }}
          path: pypi
          retention-days: 1

  merge-artifacts:
    needs: build-packages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with: # download all build artifacts
          pattern: ${{ inputs.artifact-name }}-*
          merge-multiple: true
          path: pypi
      - run: |
          sudo apt-get install -y tree
          tree pypi

      - name: Keep artifact
        run: python -c "print('DAYS=' + str(5 if '${{ github.event_name }}'.startswith('pull_request') else 0))" >> $GITHUB_ENV
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ inputs.artifact-name }}
          path: pypi
          retention-days: ${{ env.DAYS }}
          if-no-files-found: error
