name: Label conflicts

on:
  push:
    branches: ["main"]
  pull_request:
    types: ["synchronize", "reopened", "opened"]
  pull_request_target:
    types: ["synchronize", "reopened", "opened"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  triage-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: eps1lon/actions-label-merge-conflict@636b369ea34ff799b8db5182df6f19e39b2d4adb # v3.0.3
        with:
          dirtyLabel: "has conflicts"
          repoToken: ${{ secrets.GITHUB_TOKEN }}
