name: Label conflicts

on:
  push:
    branches: ["main"]
  pull_request_target:
    types: ["synchronize", "reopened", "opened"]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  triage-conflicts:
    runs-on: ubuntu-latest
    steps:
      - run: "echo skipped for now"
      - uses: mschilde/auto-label-merge-conflicts@cd484bbf0476fbe79474a937681a253e094cac3d # May 9, 2026
        with:
          CONFLICT_LABEL_NAME: "has conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAX_RETRIES: 3
          WAIT_MS: 5000
